sudo: required 

services:
  - docker

before_install:
   - docker build -f Dockerfile.dev -t objectone/docker-react .

script:
   - docker run -e CI=true objectone/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-reat"
    env: "DockerReat-env"
    bucket_name: "elasticbeanstalk-us-east-2-141138251359"
    bucket_path: "docker-reat"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


  

       